fix(amtinfo) : amtinfo command add amt ipaddr and osipaddr
tongsean9807/rpc-go pull request #2
Opened 2024-06-05 07:19 UTC by tongsean9807

2024-06-05 08:21 UTC, tongsean9807 commented
Hi,
I will set it to return 0. amt by default return 0 is the struct is empty

I have pass test a well.
![image](https://github.com/tongsean9807/rpc-go/assets/105337968/9abf6e30-fcda-49ce-8b9b-4b8f0b97ec7d)

2024-06-11 22:50 UTC, bgmckown commented
Am I overlooking something obvious here? This appears to be a redundant PR with https://github.com/tongsean9807/rpc-go/pull/1

2024-06-12 22:34 UTC, bgmckown requested changes

2024-06-12 22:34 UTC, bgmckown commented on internal/amt/commands.go
> +	OsIPAdress  string `json:"osIpAddress"`
spelling correction
```suggestion
	OsIPAddress  string `json:"osIpAddress"`
```

2024-06-12 22:34 UTC, bgmckown commented on internal/amt/commands.go
> +		OsIPAdress:  "0.0.0.0",
```suggestion
		OsIPAddress:  "0.0.0.0",
```

2024-06-12 22:34 UTC, bgmckown commented on internal/local/info.go
> +			service.PrintOutput("OS  IP Address		: " + wired.OsIPAdress)
```suggestion
			service.PrintOutput("OS  IP Address		: " + wired.OsIPAddress)
```

2024-06-12 22:34 UTC, bgmckown commented on internal/local/info.go
> +		service.PrintOutput("OS  IP Address		: " + wireless.OsIPAdress)
```suggestion
		service.PrintOutput("OS  IP Address		: " + wireless.OsIPAddress)
```

2024-06-14 03:03 UTC, bgmckown approved these changes

2024-06-14 03:24 UTC, merged